name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run_Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_standard: [11, 14, 17, 20, 23]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
    
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} | ${{ matrix.compiler }} | C++${{ matrix.cpp_standard }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GCC 13
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-13
          echo "CXX=g++-13" >> $GITHUB_ENV
          echo "CC=gcc-13" >> $GITHUB_ENV

      - name: Set up Clang 18
        if: matrix.compiler == 'clang'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-18
          echo "CXX=clang++-18" >> $GITHUB_ENV
          echo "CC=clang-18" >> $GITHUB_ENV

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S tests/ -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }} \
          -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Build
        shell: bash
        run: cmake --build build --config Debug

      - name: Run Tests
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./build/Debug/BigInt_gtest.exe --gtest_color=no --gtest_filter=*-Test_BigInt_Performance.*
          else
            ./build/BigInt_gtest --gtest_color=no --gtest_filter=*-Test_BigInt_Performance.*
          fi
